// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.Controllers.AdminController.AddClosingClaenderDetail(GlobalCalendar.MVC.Models.CompanyWiseDate)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.Controllers.HomeController.ApproveSubmitTask(GlobalCalendar.MVC.DTO.TaskDetail,System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.Controllers.HomeController.DeleteDoc(System.Int32,System.Int32)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.Controllers.HomeController.SubmitTask(GlobalCalendar.MVC.DTO.TaskDetail,System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.Controllers.LoginController.getUser~System.String")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.Controllers.LoginController.ValidateUser(GlobalCalendar.MVC.Models.UserInfo)~Microsoft.AspNetCore.Mvc.ActionResult")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.GetApprovedList(System.String)~System.Collections.Generic.List{GlobalCalendar.MVC.DTO.ListApproveTask}")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.GetApproveList(System.String)~System.Collections.Generic.List{GlobalCalendar.MVC.DTO.ListApproveTask}")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.GetFileList(GlobalCalendar.MVC.DTO.UploadFile)~System.Collections.Generic.List{GlobalCalendar.MVC.DTO.FileDownloadView}")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.GetList(System.String)~System.Collections.Generic.List{GlobalCalendar.MVC.DTO.TaskModel}")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.GetReason~System.Collections.Generic.List{GlobalCalendar.MVC.DTO.ReasonMaster}")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.GETTaskDetailApprover(System.Int32)~GlobalCalendar.MVC.DTO.TaskDetail")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.GetTaskDetailById(System.Int32)~GlobalCalendar.MVC.DTO.TaskDetail")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.PostCompnayWithTime(GlobalCalendar.MVC.Models.CompanyWiseDate)~System.Collections.Generic.List{GlobalCalendar.MVC.DTO.EmailSendingDto}")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.RejectApprover(GlobalCalendar.MVC.DTO.TaskDetail)~GlobalCalendar.MVC.DTO.EmailDetail")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.CommonRepo.SaveTaskDetail(GlobalCalendar.MVC.DTO.TaskDetail)~GlobalCalendar.MVC.DTO.EmailTemplateSender")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.SQLSERVER_HELPER.GetData(System.String,System.Collections.Generic.Dictionary{System.String,System.Object})~System.Data.DataSet")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.SQLSERVER_HELPER.GetSAPDBData(System.String,System.Collections.Generic.Dictionary{System.String,System.Object})~System.Data.DataSet")]
[assembly: SuppressMessage("Usage", "CA2200:Rethrow to preserve stack details", Justification = "<Pending>", Scope = "member", Target = "~M:GlobalCalendar.MVC.DAL.TBSDAL.GetEmployeeCodeAndName(System.String)~GlobalCalendar.MVC.Models.UserInfo")]
